version: '3.9'
services:
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-container
    expose:
      - 3000
    ports:
      - '3000:3000'
